#/*
# *********************************************
# *  314 Principles of Programming Languages  *
# *  Spring 2013                              *
# *  Authors: Ulrich Kremer                   *
# *           Hans Christian Woithe           *
# *********************************************
# */

CCFLAGS = -ggdb -Wall

all: tokenizer

tokenizer: tokenizer.c
	gcc $(CCFLAGS) tokenizer.c -o tokenizer

clean:
	rm tokenizer
